substitutions:
  _CLOUD_SDK_VERSION: 251.0.0
  _GOLANG_VERSION: 1.11.11
  _PYTHON_VERSION: 3.7.1
  _NODEJS_6_VERSION: 6.16.0
  _NODEJS_8_VERSION: 8.15.0
  _NODEJS_10_VERSION: 10.15.3
  _YARN_VERSION: 1.16.0

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/cloud-function-builder-cli
      - -f
      - cloud-function-builder/Dockerfile
      - --build-arg
      - GOLANG_VERSION=$_GOLANG_VERSION
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        runtimes=(go111 python37 nodejs6 nodejs8 nodejs10)
        for runtime in "${runtimes[@]}"; do
          docker build -t gcr.io/$PROJECT_ID/cloud-function-builder:$runtime \
            --target $runtime \
            --build-arg PROJECT_ID=$PROJECT_ID \
            --build-arg CLOUD_SDK_VERSION=$_CLOUD_SDK_VERSION \
            --build-arg GOLANG_VERSION=$_GOLANG_VERSION \
            --build-arg PYTHON_VERSION=$_PYTHON_VERSION \
            --build-arg NODEJS_6_VERSION=$_NODEJS_6_VERSION \
            --build-arg NODEJS_8_VERSION=$_NODEJS_8_VERSION \
            --build-arg NODEJS_10_VERSION=$_NODEJS_10_VERSION \
            --build-arg YARN_VERSION=$_YARN_VERSION \
            .
        done
  - name: gcr.io/$PROJECT_ID/cloud-function-builder:go111
  - name: gcr.io/$PROJECT_ID/cloud-function-builder:python37
  - name: gcr.io/$PROJECT_ID/cloud-function-builder:nodejs6
  - name: gcr.io/$PROJECT_ID/cloud-function-builder:nodejs8
  - name: gcr.io/$PROJECT_ID/cloud-function-builder:nodejs10

images:
  - gcr.io/$PROJECT_ID/cloud-function-builder:go111
  - gcr.io/$PROJECT_ID/cloud-function-builder:python37
  - gcr.io/$PROJECT_ID/cloud-function-builder:nodejs6
  - gcr.io/$PROJECT_ID/cloud-function-builder:nodejs8
  - gcr.io/$PROJECT_ID/cloud-function-builder:nodejs10
